version: "3"

services:
  
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restapi_dev
      DATABASE_SSL: "false"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    restart: on-failure
    links:
      - postgres
    build:
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CUSTOM_DATABASE_URL=host=postgres port=5432 user=postgres password=admin dbname=restapi_dev sslmode=disable
    volumes:
      - backendData:/app

  migrate:
    image: migrate/migrate
    container_name: migrations
    restart: on-failure
    volumes:
      - ./backend/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:admin@postgres:5432/restapi_dev?sslmode=disable",
        "up",
      ]
    depends_on:
      - postgres
    links:
      - postgres
  
  frontend:
    deploy:
      resources:
        limits:
          memory: 10000M
        reservations:
          memory: 2500M
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend/invest-board
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - frontendData:/app

volumes:
  dbdata:
  frontendData:
  backendData:
