name: remote ssh command
on:
  push:
    branches:
      - withDockerAll
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: login as:root
      - name: Password
        run: root@45.8.228.5's password:ZVm7DQ8nQw
      - name: Pull 
        run: cd app
        run: git pull origin withDockerAll
      - name: Docker
        run: docker-compose up -d --build  


      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }} 
      #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # - name: Deploy with rsync
      #   run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/app/
      # - name: Run docker-compose
      #   run: docker-compose up -d --build  


    