name: CI/CD
on:
  push:
    branches:
      - withDockerAll
jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check Out Repo
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Set up Docker Buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push backend
  #       id: docker_build_backend
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./backend
  #         file: ./backend/Dockerfile.prod
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/invest-board:backend_${{ github.sha }}

  #     - name: Build and push frontend
  #       id: docker_build_frontend
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./frontend/front
  #         file: ./frontend/front/Dockerfile.prod
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/invest-board:frontend_${{ github.sha }}

  #     - name: Build and push migrations
  #       id: docker_build_migrations
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./backend/migrations
  #         file: ./backend/migrations/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/invest-board:migrations_${{ github.sha }}

  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    # needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to remote server
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@$45.8.228.5
          ssh_private_key: "-----BEGIN RSA PRIVATE KEY-----
          MIIJKQIBAAKCAgEAxSTSIHK67agkYKZvssnDbjMpEvbGlmEA9U0oCen00JWJuxyc35t9UKBfH1xQAizBeeUNB7JME0obVmM4UTHG+vdgFrpJBxPB8ldAdhceUpW0sM07ASLe39UGIIuL382hOohie9w5AYru+wHpKCZ1tI6b6+UUGSEQLQB2ykTmJGpH1yFzybdBE/EoZ4J4T04+WEgDdZ/pv0kcpTS3/rDfNFkpE5Mz8sTji+TaQ+u//mK0YEOTYu4gKzllz8wUj53jZ5wT8HZiuclkQ8xGVMjSJKsooooVmGHQ72HHdCy/Cu+kuT2Y7w87ytFMSnRT5mvKXJqYHSdPbM88V+cXlsq2259rEgqEZcxVzB891awshnQIjLIknBHbu70+pF7/dKYKhF/K1BuYPSGeXgN7Y5FACYrryE+K+V3J5Hp6zCn6NraVuhqV7XF9UaqOGPL8EanvSmZaOD5KOxuSzlrYa0NnZHpTabps3/aFCVvC6OTe0f8Mj5Xl2yiyhzJq0TIZ9fL5UcGZZ7LamL9A4h6x/hLFDDIxc3Z/kiA6GGQaX72LSVAjXpUvWeraUa14JTYdBejx1VurYti73ZJ/C/GiFqZnLCRPiqyJ4P1iyineGKSiz3M0eubt0oC7dKIobWmAHzSKXdHiEYMxeTxGSQBst+zoW0TBmSg9zwbkqcM2Ahj+qOcCAwEAAQKCAgAmKgWfkHZNcaJxL2cqNlLl73OBH1K8Y9T6p9AbczYYdwpttZFM3F37EMC5YnZ+pUljHotSNRrzFQKLy7NoTHmXtfHdFHz0qMd/8ZIiCkGtfRu4qlJE2wpITIXeIQWX8sfGfAaMsco7WTkAUJNhWWip5n2awgMNBlCKVa+pYoMnA4gaxngS0a4AfUv0FdbSi3QYRQCecbGffTjVZopD/NuI18XS60lAMwtV1pzGT0ogpd0DUbGjkjOaCoeCHaDRWKBgO1/EyjY8fxcw5MesvB+qR5QbOx4JHM6EuOoSvGLTbCb4UUtc5BcQIUpik3h2f+Fx4d+WrTh7+PZWkf8ICwAw1mkwn4TnHfFmYBUkVY+xkTnLMOV3FcBz9iDjseq9DY21kby1SGHFFcFSMAontO0KBsW8zFKAsvVaoUKolcfgAJauSQmfcJLakWabUuuVic8IViMYgU8j7eQ9K4bxdWkRkpYjN15j6boz1qiL5kYcTFUnRv9U14S4I7s8hoRie1glo9ZsCwfU/xhufHYO3iTWagdhWk4zqMsxjkUPvb1dvhTWu/0xcp1dWvtXfPuizORJfrIvMDyHfn3IlBTCAXxat5qFNN8BRB6fOPf/RW4lDJ7+gSowlddr9E+orNAYjMKzJvsyGsIyveM5eE2D1ff10gHLhFC2HI/Rz3Z51HH14QKCAQEA/OuxpKh1ZE9XKDfQUUs9eNeOjuq2RtnYNFgRCzCVmZlUG0WqDL3YT5ERPLip0TbNKVv4hvz/HOd+8hiMoFb8qnaXS1ks74Zqqc0/8a+ob6Ytt0LIYo8F2pz/NwTd9I/JzHkXeUX/DdfQL3bGK+1HWa/03b6cds7l0IXvNo5iGxeMhSV9G3wY5HsUjhadY4TwGSZxuLJ1xS52uSK58B4+B3adsoZcnIYCvha//4HUP8LxY7k0k6t+yRMopZG0dyDgAnaHTwRTUHTRIcxPG+QOS08g11j4qcb/FL1C3pvP+aXjwlkhdLcaoYKij9RyWTsoGIFtFUXRme+G4ZCsqoE8lwKCAQEAx4tH7XxnKGSkWogZ13/nHm9vhlkdE6NHgXU9DLEMcYoV/JmGDF7Awv2putQVenJilQVRTj+0xVUjRollmtxGU5Qr9LXAKSJnT4FKx2jFsjaBP5QVojsSciGDhFs1ukzhP78gCoR1hLtlqyt0uuFjNXwrvI9eCNh6khy7CzSMmtSTA1jwzAleCZj0l2+0nx0mZDDFx0Dp7jpL5sNOLD2n9URQraIpE4OLw+HrrIErJyIhT3cOXBKdj4EspbqVl/i/rE4mq03b51POD3NDUh1R26RQrMFO8/Nk1IOU/iyUi3qamCJFBxEHkxO63qBhbuAxval90EFUL6M5xyVrKkBwMQKCAQEAwEnpe0hgR+1SVE9q4AOWLuOjjODByEgjalhyTNGZS3gZS8rBKILFjGi8dC/pXBiQDpvP7cE3rCAMkb88W0MHQgp7qFuaIFlPit1zeiqUop3zL9tkQhp+1uB54LigjykqwXxm7lrbOQkVTKC+tfLmRjfSsSwUBPf0HX9WiWHjELnsqeYAof7NZhh1XjmvW1RcvqJN36A+jbVvqf3O49H6Uu5JossoahAw0Zi2TGnGltt9btYGNSczc2hPhOGsFM43wWegI+Ej/o1x2oJcutW+UF9OlqscEugqUvg5eMl5a1JGQSJGn1f+tUB+m19nuJOTPl5YMs4sNx62q5O00sUC7QKCAQEAg8MBtNyflXmXWTxjq/wGFf/JabIwVAZOMjrDHD1QlSx0Rj7t1/89U8SCLh7bK+aaGALR5FSGvoLwbyRM1kw7l/bQa58UC1VvWH1sbm5NlNcO03eqLVzKWlis6ln8CU+4sQo4UxmSLBo+ER/5zWkExI2Ap9sXYcnobdDQ5Z5GdfqGNQCmyGQrFzVL1S9q2mI6NpBKGL9ReQA/nFo8pVP1MyxwBad9big/wxHMODV21DliO4HHFp8oMVk/rROesiIMFu/n8tfPrFmXSHZ47qDzq5A9wUVIKCgA3Z8hZBD16YAE0w5V/EuPb9voWhcXH0qlLbLcpAZvW6FxhoG72MOCEQKCAQAS5iBaegyEG09T+qfZZ4h1iOEAX4dqatrS2MPvCnj4CQTCRXp+3hMD/+xxO4uElm0Zy8YAmzxOC+WPrHHpFRwaWTB8yrz/5t7cpIG61ylYbK+ERHpqs4eK7KgSPSYhyRv/UDu/6y2doNT6MW+bIR55Nyt/kQiMJcaUD6k8m1RHRNh5am8fm+6xm/NcQYTEoX2OW9IDo8GzxxztaMN/pVSjYLAKsWiPrzWma8s9hNMb+mWhfzR/IyY0GzVcgP2mO2eznCAfQOIkEyD+8vOX+dDjfQFPlV/uawaC4RLgFlYhei/tjYoghxyRS+8rbuDOeC6ihq8feWlClN7q2V9gi7lu-----END RSA PRIVATE KEY-----"
          ssh_public_key: 45.8.228.5 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJsuc8b7F1EnfiKrKN3vDE7FGgblYbV1TDOQ3tKn8wbm6H+mOD7PlkauHyfW09XCXhvTDHe8bzxq0c9add6WtvM=
          deployment_mode: docker-compose
          stack_file_name: docker-compose.prod.yaml
          args: up -d -build
          docker_prune: true
          pull_images_first: true
