name: CI/CD
on:
  push:
    branches:
      - withDockerAll
jobs:

   build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./Dockerfile.prod
          push: true
          tags: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs_backend.$GITHUB_RUN_ID
      
      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/front
          file: ./Dockerfile.prod
          push: true
          tags: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs_frontend.$GITHUB_RUN_ID

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.PROVERKA }}
      #     script: |
      #       whoami
      #       cd app
      #       git pull origin withDockerAll
      #       docker-compose -f docker-compose.prod.yml up -d --build




  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install SSH Key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.PROVERKA }} 
  #         name: proverka
  #         known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
  #     - name: Adding Known Hosts
  #       run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  #     - name: Deploy with rsync
  #       run: rsync -avzr ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/app/
  #     # - name: Run docker-compose
  #     #   run: docker-compose up -d --build  


    