name: remote ssh command
on:
  push:
    branches:
      - withDockerAll
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROVERKA }} 
          name: proverka
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avzr ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/app/
      # - name: Run docker-compose
      #   run: docker-compose up -d --build  


    